services:
  # A web service for the Telegram bot
  - type: web
    name: unimatch-ethiopia
    env: python
    region: ohio
    plan: free
    buildCommand: >
      pip install email-validator==2.1.0 flask==3.0.2 flask-sqlalchemy==3.1.1 
      gunicorn==23.0.0 psycopg2-binary==2.9.9 
      python-telegram-bot==20.8 sqlalchemy==2.0.29
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CONFESSION_CHANNEL_ID
        sync: false
      - key: CONFESSION_CHANNEL_USERNAME
        sync: false
      - key: OFFICIAL_CHANNEL_ID
        sync: false
      - key: OFFICIAL_CHANNEL_USERNAME
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: REQUIRE_CONFESSION_APPROVAL
        value: "True"
      - key: REQUIRE_CHANNEL_MEMBERSHIP
        value: "True"
      - key: ENABLE_NOTIFICATIONS
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: unimatch-db
          property: connectionString

databases:
  - name: unimatch-db
    plan: free
    region: ohio
    databaseName: unimatch_ethiopia
    user: unimatch